<?php

use App\Models\Aspirant\Aspirant;
use Faker\Generator as Faker;

/*
|--------------------------------------------------------------------------
| Model Factories
|--------------------------------------------------------------------------
|
| This directory should contain each of the model factory definitions for
| your application. Factories provide a convenient way to generate new
| model instances for testing / seeding your application's database.
|
*/

$factory->define(Aspirant::class, function (Faker $faker) {
    

    $political_parties = 
    [
                        'Orange Democratic Movement',                
                        'Federal Party Of Kenya',                    
                        'Economic Freedom Party',                    
                        'Shirikisho Party Of Kenya',                 
                        'United Democratic Party',                   
                        'Thirdway Alliance Kenya',                   
                        'The National Vision Party',                 
                        'Social Democratic Party Of Kenya',          
                        'Safina',                                    
                        'Progressive Party Of Kenya',                
                        'Peoples Empowerment Party',                 
                        'Peoples Democratic Party',                  
                        'Party Of National Unity',                   
                        'Party Of Independent Candidates Of Kenya',  
                        'Party Of Democratic Unity',                 
                        'Party For Development And Reform ',         
                        'New Democrats',                             
                        'National Rainbow Coalition - Kenya',        
                        'Nationa Rainbow Coalition',                 
                        'Muungano Party',                            
                        'Mazingira Greens Party Of Kenya',           
                        'Maendeleo Democratic Party',                
                        'Maendeleo Chap Chap Party',                 
                        'Kenya Patriots Party',                      
                        'Kenya African National Union',              
                        'Jubilee',                                   
                        'Green Congress Of Kenya',                   
                        'Frontier Alliance Party',                   
                        'Forum For Restoration Of Democracy - Kenya',
                        'Farmers Party',                             
                        'Empowerment And Liberation Party',          
                        'Devolution Party Of Kenya',                 
                        'Democratic Congress',                       
                        'Citizens Convention Party',                 
                        'Chama Mwangaza Daima',                      
                        'Chama Cha Uzalendo',                        
                        'Amani National Congress',                   
                        'Agano Party',     
    ];

    $electoral_area = 
    [
         'KAMUKUNJI',           
         'WESTLANDS',           
         'DAGORETTI NORTH',     
         'ROYSAMBU',            
         'STAREHE',             
         'LANGATA',             
         'DAGORETTI SOUTH ',    
         'KASARANI',            
         'RUARAKA',             
         'KIBRA',               
         'MATHARE',             
         'KISAUNI',             
         'MVITA',               
         'JOMVU',               
         'NYALI',               
         'LIKONI',              
         'KINANGO',             
         'MATUGA',              
         'LUNGA LUNGA',         
         'MSAMBWENI',           
         'KALOLENI',            
         'GANZE',               
         'KILIFI NORTH',        
         'KILIFI SOUTH',        
         'MAGARINI',            
         'RABAI',               
         'MALINDI',             
         'GALOLE',              
         'BURA',                
         'GARSEN',              
         'LAMU WEST',           
         'LAMU EAST',           
         'WUNDANYI',            
         'VOI',                 
         'MWATATE',             
         'TAVETA',             
         'BALAMBALA',           
         'IJARA',               
         'DAADAB',              
         'GARISSA TOWNSHIP',    
         'FAFI',                
         'LAGDERA',             
         'WAJIR WEST',          
         'WAJIR NORTH',         
         'WAJIR SOUTH',         
         'TARBAJ',              
         'ELDAS',               
         'WAJIR EAST',          
         'MANDERA SOUTH',       
         'MANDERA NORTH',       
         'MANDERA WEST',        
         'BANISSA',             
         'NORTH HORR',          
         'MOYALE',              
         'LAISAMIS',            
         'SAKU',                
         'ISIOLO NORTH',        
         'ISIOLO SOUTH',        
         'NORTH IMENTI',        
         'TIGANIA WEST',        
         'SOUTH IMENTI',        
         'BUURI',               
         'IGEMBE SOUTH',        
         'IGEMBE CENTRAL',      
         'TIGANIA EAST',        
         'CENTRAL IMENTI',      
         'IGEMBE NORTH',        
         'MAARA',               
         'THARAKA',             
         'CHUKA/IGAMBANGOMBE', 
         'RUNYENJES',           
         'MBEERE NORTH',        
         'MANYATTA',            
         'MBEERE SOUTH',        
         'KITUI EAST',          
         'KITUI SOUTH ',        
         'KITUI CENTRAL',       
         'YATTA',               
         'MACHAKOS TOWN',       
         'MATUNGULU',           
         'MWALA',               
         'MASINGA',             
         'KANGUNDO',            
         'MAVOKO',              
         'KATHIANI',            
         'KIPIPIRI',            
         'KINANGOP',            
         'NDARAGWA',            
         'KIENI',               
         'MATHIRA',             
         'OTHAYA',              
         'TETU',                
         'MUKURWEINI',          
         'NYERI TOWN',          
         'GICHUGU',             
         'KIRINYAGA CENTRAL',   
         'NDIA',                
         'MWEA',                
         'MATHIOYA',            
         'KANDARA',             
         'MARAGWA',             
         'KANGEMA',             
         'KIGUMO',              
         'KIHARU',              
         'GATUNDU NORTH',       
         'KABETE',              
         'KIAMBAA',             
         'GITHUNGURI',          
         'THIKA TOWN',          
         'GATANGA',             
         'KIKUYU',              
         'LIMURU',              
         'GATUNDU SOUTH',       
         'LARI',                
         'JUJA',                
         'RUIRU',               
         'KIAMBU',              
         'TURKANA NORT',       
         'TURKANA EAST',        
         'TURKANA CENTRAL',              
         'TURKANA WEST',        
         'LOIMA',               
         'TURKANA SOUTH',       
         'KAPENGURIA',          
         'SIGOR',               
         'KACHELIBA',           
         'POKOT SOUTH',        
         'MARAKWET WEST',       
         'SAMBURU NORTH',       
         'SAMBURU WEST',        
         'SAMBURU EAST',        
         'AINABKOI',            
         'MOIBEN',              
         'SOY',                 
         'TURBO',               
         'KESSES',              
         'KAPSERET',            
         'MARAKWET EAST',       
         'KEIYO NORTH',         
         'KEIYO SOUTH',         
         'MOSOP',               
         'EMGWEN',              
         'ALDAI',               
         'CHESUMEI',            
         'BARINGO CENTRAL',     
         'BARINGO NORTH',       
         'MOGOTIO',             
         'ELDAMA RAVINE',       
         'BARINGO SOUTH',       
         'TIATY',               
         'LAIKIPIA NORTH',      
         'SUBUKIA',             
         'KURESOI SOUTH',       
         'NJORO',               
         'NAKURU TOWN EAST',    
         'RONGAI',              
         'NAIVASHA',            
         'GILGIL',              
         'NAKURU TOWN WEST',    
         'KURESOI NORTH',       
         'MOLO',                
         'BAHATI',              
         'NAROK SOUTH',         
         'NAROK NORTH',         
         'KILGORIS',            
         'NAROK WEST',          
         'EMURUA DIKIRR',       
         'NAROK EAST',          
         'KAJIADO CENTRAL',     
         'KAJIADO WEST',        
         'KAJIADO EAST',       
         'KAJIADO SOUTH',      
         'KAJIADO NORTH',      
         'KIBWEZI WEST',       
         'MBOONI',             
         'MAKUENI',            
         'KAITI',              
         'KILOME',             
         'KIBWEZI EAST',       
         'BELGUT',             
         'KIPKELION WEST',     
         'SIGOWET/SOIN',       
         'KIPKELION EAST',     
         'AINAMOI',            
         'KONOIN',             
         'SHINYALU',           
         'MATUNGU',            
         'BUTERE',             
         'KHWISERO',           
         'MALAVA',             
         'IKOLOMANI',          
         'LURAMBI',            
         'MUMIAS WEST',        
         'NAVAKHOLO',          
         'MUMIAS EAST',        
         'HAMISI',             
         'SABATIA',            
         'LUANDA',             
         'VIHIGA',             
         'EMUHAYA',            
         'KANDUYI',  
         'MT. ELGON',
         'KIMILILI', 
         'SIRISIA',  
         'BUMULA',   
         'TONGAREN',            
         'WEBUYE EAST',         
         'KABUCHAI',            
         'WEBUTE WEST',         
         'TESO NORTH ',         
         'BUTULA',              
         'FUNYULA',             
         'TESO SOUTH',          
         'MATAYOS',             
         'NAMBALE',             
         'BUDALANGI',           
         'UGENYA',              
         'RARIEDA',             
         'BONDO',               
         'UGUNJA',              
         'GEM',                 
         'ALEGO USONGA',        
         'RANGWE',              
         'KASIPUL',             
         'SUBA',                
         'KARACHUONYO',         
         'KABONDO KASIPUL',     
         'MBITA',               
         'NDHIWA',              
         'HOMA BAY TOWN',       
         'KURIA EAST',          
         'NYATIKE',             
         'AWENDO',              
         'KURIA WEST',          
         'URIRI',               
         'RONGO',               
         'NYARIBARI CHACHE',    
         'KITUTU CHACHE NORTH', 
         'NYARIBARI MASABA',    
         'BOMACHOGE CHACHE',    
         'BOBASI',              
         'BOMACHOGE BORABU',    
         'BONCHARI',            
         'KITUTU CHACHE SOUTH', 
         'SOUTH MUGIRANGO',     
         'BURETI',              
         'CHEPALUNGU',          
         'BOMET EAST',          
         'SOTIK',               
         'BOMET CENTRAL',       
         'NORTH MUGIRANGO',     
         'WEST MUGIRANGO',      
         'KITUTU MASABA',       
         'BORABU',              
         'NYAKACH',             
         'SEME',                
         'NYANDO',              
         'KISUMU WEST',         
         'KISUMU EAST',         
         'MUHORONI',            
         'KISUMU CENTRAL',      
         'LUGARI',              
         'ENDEBESS',            
         'KWANZA',              
         'SABOTI',              
         'CHERANGANY',          
         'KIMININI',            
         'LIKUYANI',            
         'LAFEY',               
         'MANDERA EAST',        
         'EMBAKASI WEST',       
         'EMBAKASI EAST',       
         'EMBAKASI NORTH',      
         'EMBAKASI CENTRAL',    
         'EMBAKASI SOUTH',      
         'MAKADARA',            
         'MWINGI WEST',         
         'MWINGI CENTRAL',      
         'MWINGI NORTH',        
         'OL JOROK',            
         'OL KALOU',            
         'SUNA EAST',           
         'SUNA WEST',           
         'LAIKIPIA WEST',       
         'LAIKIPIA EAST',       
         'CHANGAMWE',           
         'KITUI RURAL',         
         'KITUI WEST',          
         'TINDERET',            
         'NANDI HILLS',  
    ];
    return [
        'full_name'            => $faker->name,
        'uuid'                 => Str::uuid()->toString(),
        'political_party'       => $political_parties[rand(0, count($political_parties) - 1)],
        'electoral_position'   => 'Member of National Assembly',
        'electoral_area'       => $electoral_area[rand(0, count($electoral_area) - 1)],
    ];
});
   